### ISSUE TITLE
报错，找不到模块

### ISSUE THREAD

**Issue by keyuan15** [saucer-man/unauth_scan#1]
PS D:\unauth_scan> pip3 install -r requirement.txt
Requirement already satisfied: pymysql in c:\python37\lib\site-packages (from -r .\requirement.txt (line 1)) (0.9.3)
Requirement already satisfied: cx_Oracle in c:\python37\lib\site-packages (from -r .\requirement.txt (line 2)) (7.2.3)
Requirement already satisfied: psycopg2 in c:\python37\lib\site-packages (from -r .\requirement.txt (line 3)) (2.8.4)
PS D:\unauth_scan> python3 .\unauth.py
[-]  module not found!
[-] try: pip install -r requirement.txt
PS D:\unauth_scan>

**Comment by saucer-man** [comment]
已修正，还需要安装pysmb
